### ISSUE TITLE
fetch-height command returns value is not in a JSON format.

### ISSUE THREAD

**Issue by sikamedia** [mvs-org/metaverse#137]
mvs-cli fetch-height returns an Integer value which is not in a valid JSON format.

```
./mvs-cli  fetch-height
199573
```
Suggestion:  {"height": 199573}

**Comment by betachen** [comment]
rename as getheight in version v0.7.2;

**Comment by betachen** [comment]
remain 'fetch-height' for compatible.
Strongly recommends  to use 'getheight' after v0.7.3
