### ISSUE TITLE
[Help offered] - Website

### ISSUE THREAD

**Issue by albsa** [mvs-org/metaverse#150]
Hello guys / @betachen @wdyoschina ,

I would like to offer my help as JS engineer - especially React.js to develop/improve the website.
Please send me your email so we can have a conversation about it.

**Comment by betachen** [comment]
@albsa Hi, this is my email address: hao.chen@viewfin.com
i will help you for this.

**Comment by albsa** [comment]
@betachen Got it, just send you an email.

**Comment by albsa** [comment]
@betachen Let me know if you received my e-mail! Talk to you soon

**Comment by betachen** [comment]
Hi, thank you for your email.
Sent already.
