### ISSUE TITLE
127.0.0.1:8820 - "Not Found" error

### ISSUE THREAD

**Issue by rewrewby** [mvs-org/metaverse#155]
After compiling and running "mvsd", when I point to http://127.0.0.1:8820 in browser - it's returns "Not Found" text message.
How this can be fixed?

**Comment by betachen** [comment]
Hi, you have to install https://github.com/mvs-org/mvs-htmls in work path.

work path:
```
Windows   : %HOMEPATH%\AppData\Roaming\Metaverse
Apple OSX : ~/Library/Application\ Support/Metaverse
Linux/Uinx: ~/.metaverse
```

**Comment by wdyoschina** [comment]
too long no respons. so i think your issue is resolved. reopen it if any issue.
