### ISSUE TITLE
mvsd ignores configuration file

### ISSUE THREAD

**Issue by baaa** [mvs-org/metaverse#156]
the configuration file supplied by --config option is completely ignored. It is not possible to change any of these parameters at the moment.

**Comment by betachen** [comment]
@baaa 
Hi, we suggest that using mvs.conf to configure mvsd.
you can see global setting to configure in file https://github.com/mvs-org/metaverse/blob/master/etc/mvs.conf

**Comment by wdyoschina** [comment]
too long no respons. so i think your issue is resolved. reopen it if any issue. Thank you!
