### ISSUE TITLE
getnewaddress 10000 addresses take 11 minutes

### ISSUE THREAD

**Issue by betachen** [mvs-org/metaverse#162]
getnewaddress 10000 addresses take 11 minutes

**Comment by betachen** [comment]
in file getnewaddress.cpp:
```cpp
blockchain.store_account(acc);         
blockchain.store_account_address(addr);
```
these 2 lines take 90% time of executing time.

**Comment by betachen** [comment]
@ydxt25 closed need comments.

**Comment by wdyoschina** [comment]
performance optimized now. so close it !
