### ISSUE TITLE
Wallet is telling me "password is invalid" 

### ISSUE THREAD

**Issue by steelliberty** [mvs-org/metaverse#165]
If I use the wrong password I get "Password Failed" -- If you use the correct password I get "Password Invalid" -- 

I hope this forum might be the correct place for this question, but if not, please point me to the correct url -- 

Thank you, 

Jack

**Comment by sikamedia** [comment]
I guess you should have upgraded to the latest version. (v0.7.1) ? 

The most important thing is "your account mnemonic", not username and password. 

Try to register and import from private key again. 

Leave message if you need more help.

**Comment by steelliberty** [comment]
Thank you,

I will try that -  I am currently  using Mac OS version 7.0

**Comment by sikamedia** [comment]
Mac OS version 7.0 is too old to install the official version.

**Comment by steelliberty** [comment]
I noticed that a blockchain version of the Mac OS is not available, I am
now downloading the standard wallet -- this link is broken
http://newmetaverse.org/mvs-download/mvs-macOSX-x86_64-database-v0.7.1.pkg

**Comment by wdyoschina** [comment]
agree with sikamedia,  Try to use your "account mnemonic" to register and import from private key.
another way is download newest wallet.
https://mvs.org/#download

**Comment by wdyoschina** [comment]
sikamedia and wdyoschina provide suggenstion. but too long no respons. so i think your issue is resolved. reopen it if any issue.
Thank you !
