### ISSUE TITLE
Wallet gives errors

### ISSUE THREAD

**Issue by Frederikvdg** [mvs-org/metaverse#166]
Hi,

Downloaded the metaverse wallet yesterday.
It doesn't start up anymore and fails. Starts the msDOS screen and then just closes it.

Error file:
20171023T085905 WARNING [server] ================= startup ==================
20171023T085905 ERROR [server] ================= startup ==================
20171023T085905 FATAL [server] ================= startup ==================
20171023T092200 WARNING [server] ================= startup ==================
20171023T092200 ERROR [server] ================= startup ==================
20171023T092200 FATAL [server] ================= startup ==================

Debug File:

20171023T085905 INFO [server] mvsd version 0.7.1
20171023T085905 DEBUG [server] ================= startup ==================
20171023T085905 INFO [server] ================= startup ==================
20171023T085905 INFO [server] Using config file: "C:\Users\*\AppData\Roaming\Metaverse"
20171023T085905 INFO [database]  database version = 0.6.2
20171023T085905 INFO [database]  mvsd db version = 0.6.2
20171023T085905 INFO [server] Please wait while the server is starting...
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\block_table" [36455022] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\block_index" [1106022] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\history_table" [583264560] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\history_rows" [17627263] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\spend_table" [1368663660] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\stealth_rows" [4] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\transaction_table" [1200000546] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_table" [120558] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\asset_table" [120237] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\address_asset_table" [583264560] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\address_asset_row" [74449246] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_asset_table" [39996] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_asset_row" [4] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_address_table" [60036] (4096)
20171023T085905 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_address_rows" [1101] (4096)
20171023T085905 INFO [node] Starting manual session.
20171023T085905 DEBUG [network] Seeding is not required because there are 137 cached addresses.
20171023T085905 INFO [server] Seeding is complete.
20171023T085905 INFO [node] Node start height is (96488).
20171023T085905 INFO [node] Starting inbound session.
20171023T085905 INFO [node] Starting outbound session.
20171023T085905 DEBUG [server] Applied address authentication to socket [query]
20171023T085905 INFO [server] Bound public query service to tcp://*:9091
20171023T085905 DEBUG [server] Connected public notification worker to inproc://public_notify
20171023T085905 DEBUG [server] Connected public query worker to inproc://public_query
20171023T085905 INFO [server] Server is started.
20171023T085905 INFO [server] http server listen on (127.0.0.1:8820)
20171023T085923 DEBUG [node] Potential transaction from [178.62.83.250:5251].8bea5a70e2ff115c54a37115214b4a77aa50e4c748356daf600097b9d4208a05
20171023T092200 INFO [server] mvsd version 0.7.1
20171023T092200 DEBUG [server] ================= startup ==================
20171023T092200 INFO [server] ================= startup ==================
20171023T092200 INFO [server] Using config file: "C:\Users\*\AppData\Roaming\Metaverse"
20171023T092200 INFO [database]  database version = 0.6.2
20171023T092200 INFO [database]  mvsd db version = 0.6.2
20171023T092200 INFO [server] Please wait while the server is starting...
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\block_table" [36455022] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\block_index" [1106022] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\history_table" [583264560] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\history_rows" [17627263] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\spend_table" [1368663660] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\stealth_rows" [4] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\transaction_table" [1200000546] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_table" [120558] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\asset_table" [120237] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\address_asset_table" [583264560] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\address_asset_row" [74449246] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_asset_table" [39996] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_asset_row" [4] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_address_table" [60036] (4096)
20171023T092200 DEBUG [database] Mapping: "C:\Users\*\AppData\Roaming\Metaverse\mainnet\account_address_rows" [1101] (4096)
20171023T092200 INFO [node] Starting manual session.
20171023T092200 DEBUG [network] Seeding is not required because there are 137 cached addresses.
20171023T092200 INFO [server] Seeding is complete.
20171023T092200 INFO [node] Node start height is (96488).
20171023T092200 INFO [node] Starting inbound session.
20171023T092200 INFO [node] Starting outbound session.
20171023T092200 DEBUG [server] Applied address authentication to socket [query]
20171023T092200 INFO [server] Bound public query service to tcp://*:9091
20171023T092200 DEBUG [server] Connected public notification worker to inproc://public_notify
20171023T092200 DEBUG [server] Connected public query worker to inproc://public_query
20171023T092200 INFO [server] Server is started.
20171023T092200 INFO [server] http server listen on (127.0.0.1:8820)

What is the problem, what can I do about it?

Thx!

**Comment by sikamedia** [comment]
Have you tried this http://newmetaverse.org/mvs-download/mvs-win64-database-v0.7.1.exe  ?   This version is with blockchain data.

**Comment by wdyoschina** [comment]
maybe your data corruption, IMPORTANT : make sure remember your account mnemonic!
two suggestion.
1. download newest wallet with blockdata inside on mvs.org
2. rename C:\Users\$username\AppData\Roaming\Metaverse\mainet to another name. for exampel : mainet.bak.
warning : make sure you have saved your account mnemonic !

**Comment by Frederikvdg** [comment]
Did both:

Took a backup of my mainet + downloaded the blockchain data version.
Worked.
Thanks guys!
