### ISSUE TITLE
It does not show the proper asset description characters in V0.7.1 wallet. 

### ISSUE THREAD

**Issue by sikamedia** [mvs-org/metaverse#167]
![assets](https://user-images.githubusercontent.com/1304031/31968737-686b5a2c-b912-11e7-8806-cc5902716dac.jpeg)

**Comment by sikamedia** [comment]
It shows correctly in mymvs.info. 
![mymvs info](https://user-images.githubusercontent.com/1304031/31968757-83870162-b912-11e7-8ff3-220f3da6cd62.jpeg)

**Comment by wdyoschina** [comment]
It shows ok in my wallet.  save your account mnemonic and try upgrade your wallet to 0.7.1 .

**Comment by wdyoschina** [comment]
i test this issue on v0.7.1. it is resolved. so i closed it.
