### ISSUE TITLE
"mnemonic to seed command" error process enhance when invalid mnemonic words as inputs

### ISSUE THREAD

**Issue by wdyoschina** [mvs-org/metaverse#173]
return at once when invalid mnemonic words as input

**Comment by Mandegra000** [comment]
Hi wdyoschina,

Could this issue result in someone with the correct 24 words to not be able to successfully import? 

What issues could exist with the wallet due to the "mnemonic to seed command error" ?

Thank you in advance for the help!

**Comment by wdyoschina** [comment]
Could this issue result in someone with the correct 24 words to not be able to successfully import?
A : no , this issue just  for " return detail error message" when invalid mnemonic words as input. it is impossible that the correct 24 words are not be able to successfully import.

What issues could exist with the wallet due to the "mnemonic to seed command error" ?
A : no any issue to the wallet mnemonic function, this change just enhance the error process when invalid mnemonic words as input. you can refer to our code.

**Comment by wdyoschina** [comment]
this bug is corrected now. so close it!
