### ISSUE TITLE
different ballance in the wallet and in the blockchain

### ISSUE THREAD

**Issue by muhammad-05** [mvs-org/metaverse#177]
I want to contact the developer of the etp.
I have a problem.
Why after finding orfan in my wallet the amount is not changed and https://explorer.mvs.org/#!/adr/MF4d9NKieuJFSRRY79fymLJA2YqXnV6Ewq
increases as the block?
Because of this, I have a different ballance in https://explorer.mvs.org/#!/adr/MF4d9NKieuJFSRRY79fymLJA2YqXnV6Ewq 
and the purse in 6 coins

**Comment by wdyoschina** [comment]
Hi muhammad-05,
i searched the address MF4d9NKieuJFSRRY79fymLJA2YqXnV6Ewq, just find 0 etp and not transaction on it.
connect us if the issue still exist and a detail issue description expected. Thanks !

**Comment by muhammad-05** [comment]
Recently found orfan, the result has not changed. how was the difference in the 2 units, it is.
today sedan analysis on the wallet was found blocks and payouts.
Noticed that after catching orfan block, my balance is reduced in the explorer and in wallet .. ie there were 50 coins in the account, got a block orfan look at the balance, I have 47,15

**Comment by muhammad-05** [comment]
Again on the blockchain error, can't check wallet balance, caught a few blocks. again, not enough to balance the reward for 1 unit.
The forums will begin to describe the problems.
Please correct the problem and restore me extra coins.
Since I have a pool and there blocks to catch the miners, I had with of pocket to pay the miners for your mistakes on the blockchain.

**Comment by muhammad-05** [comment]
it turns out that, at the time of the problems in your network, blocks are confirmed and the award is not credited. please fix this problem and compensate our losses.
I wrote to the contact with the official website, they are sent here. I hope help is expected

**Comment by muhammad-05** [comment]
Again on the blockchain error, can't check wallet balance, caught a few blocks. again, not enough to balance the reward for 1 unit.
The forums will begin to describe the problems.
Please correct the problem and restore me extra coins.
Since I have a pool and there blocks to catch the miners, I had with of pocket to pay the miners for your mistakes on the blockchain.

it turns out that, at the time of the problems in your network, blocks are confirmed and the award is not credited. please fix this problem and compensate our losses.
I wrote to the contact with the official website, they are sent here. I hope help is expected

yesterday was again the same problem, the statistics of finding blocks on my pool very well, but again payment is not enough balance on 1 unit, tried to check the stats of my purse, blogexplosion didn't work. but the point is that, again, does not grasp the balance, found Out that the orphan is not being correctly handles it.
but in my understanding, reward for some blocks are not charged.
I have this situation because of the lack of balance I had to pay the 25 miners etp buying on the exchange and the Bay to Poole

>Пятница, 17 ноября 2017, 9:29 +03:00 от wdyoschina <notifications@github.com>:
>
>Hi muhammad-05,
>i searched the address MF4d9NKieuJFSRRY79fymLJA2YqXnV6Ewq, just find 0 etp and not transaction on it.
>connect us if the issue still exist and a detail issue description expected. Thanks !
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Магомед Хайбулаев

**Comment by muhammad-05** [comment]
https://explorer.mvs.org/#!/blk/728039  
this block got me, but it is recorded on the other. why?
http://etp.mole-pool.net:84/#/blocks/immature  

due to the fact that the wrong block is considered I grip the balance for the payment

**Comment by muhammad-05** [comment]
because of this I had to edit the database unit as orfan

**Comment by jiraiyav5** [comment]
Your pool hashrate is too small .According to the Ghost protocol, the block you mined have been overwrite by other big hasrate miner. Maybe network problem also could  lead to this high orphan rate.

**Comment by luozhaohui** [comment]
Agree with @jiraiyav5. 
Close this issue.
