### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by RyanF109** [mvs-org/metaverse#188]
`[ 4%] Building CXX object src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/chain/attachment/account/account.cpp.o cd /home/anonymous/Applications/metaverse/build/src/lib/bitcoin && /usr/bin/c++ -DBC_STATIC=1 -I/home/anonymous/Applications/metaverse/contrib -I/home/anonymous/Applications/metaverse/include -I/home/anonymous/Applications/metaverse/src/lib/consensus/clone -std=c++11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG -o CMakeFiles/bitcoin_static.dir/chain/attachment/account/account.cpp.o -c /home/anonymous/Applications/metaverse/src/lib/bitcoin/chain/attachment/account/account.cpp /home/anonymous/Applications/metaverse/src/lib/bitcoin/chain/attachment/account/account.cpp: In member function ‘uint64_t libbitcoin::chain::account_multisig::serialized_size() const’: /home/anonymous/Applications/metaverse/src/lib/bitcoin/chain/attachment/account/account.cpp:146:5: error: this ‘for’ clause does not guard... [-Werror=misleading-indentation] for(auto& each : cosigner_pubkeys_) ^~~ /home/anonymous/Applications/metaverse/src/lib/bitcoin/chain/attachment/account/account.cpp:148:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’ size += (description_.size() + 9); ^~~~ cc1plus: all warnings being treated as errors src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/build.make:65: recipe for target 'src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/chain/attachment/account/account.cpp.o' failed make[2]: *** [src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/chain/attachment/account/account.cpp.o] Error 1 make[2]: Leaving directory '/home/anonymous/Applications/metaverse/build' CMakeFiles/Makefile2:302: recipe for target 'src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/all' failed make[1]: *** [src/lib/bitcoin/CMakeFiles/bitcoin_static.dir/all] Error 2 make[1]: Leaving directory '/home/anonymous/Applications/metaverse/build' Makefile:141: recipe for target 'all' failed make: *** [all] Error 2`

**Comment by wdyoschina** [comment]
Hi RyanF109,
could your provide detail info on the compile error?
1. os name and versoin
2. compiler name and version

**Comment by betachen** [comment]
Notice
> /home/anonymous/Applications/metaverse/src/lib/bitcoin/chain/attachment/account/account.cpp:148:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’ size += (description_.size() + 9); ^~~~ cc1plus: all warnings being treated as errors 

It seems your comipler not support c++ 11;
please upgrade your compiler.

@RyanF109

**Comment by jowenshaw** [comment]
I met the same problem as yours, that's because my gcc version is gcc6.
The real problem is that there exists tabs and spaces at the same time in the repository. 
We will solve this later by replace tabs with spaces, and always use braces in the if/for/while... statement.
**This question is solved now, ref. to commit `b450b522062773982888f870743c6b1ec3162b4d`.**
You can merge the latest master branch to solve it. 
Hope this can help you.

**Comment by betachen** [comment]
solved.
