### ISSUE TITLE
Adjust the ETP reward rate of Deposit function

### ISSUE THREAD

**Issue by OffZhen** [mvs-org/metaverse#203]
Need to change inflation rate by adjusting reward rate. If Metaverse use the current reward rate, there are few problems:
1. The inflation rate is a little bit high
2. If large amount ETP deposit expire, they may have an impact on ETP price

Solution 1: Fix a relative lower reward rate
Solution 2: Adjustable reward rate

Current reward rate:
<img width="861" alt="8be7ebd4-cf51-4e1f-aece-d0125d9d544e" src="https://user-images.githubusercontent.com/15893135/33869224-9582fadc-df42-11e7-88d5-9a7997d1134c.png">

**Comment by sikamedia** [comment]
Is it possible to have adjustable reward rate which is correlated to [Central banks - summary of current interest rates](http://www.global-rates.com/interest-rates/central-banks/central-banks.aspx)?

**Comment by canguruhh** [comment]
closed as deposit does not exists anymore
