### ISSUE TITLE
connect[127.0.0.1:8820/rpc] failed: Connection refused

### ISSUE THREAD

**Issue by bapparabi** [mvs-org/metaverse#211]
miningadmin@metaverse:~/etp/mvs-linux-x86_64-v0.7.2$ ./mvs-cli getnewaccount testaccount testaccount
connect[127.0.0.1:8820/rpc] failed: Connection refused

why i am getting this error when i try to start the cli to make new address

**Comment by sikamedia** [comment]
Have you run mvsd?

**Comment by bapparabi** [comment]
yes it running
