### ISSUE TITLE
2017/12/16 04:47:31 Error while refreshing pending block on main: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by bapparabi** [mvs-org/metaverse#212]
2017/12/16 04:47:31 Error while refreshing pending block on main: invalid character '<' looking for beginning of value

why i am getting this error when i try to run pool

**Comment by sikamedia** [comment]
Please tell what you have done which causes the error, step by step (context). Otherwise no one can help you?

**Comment by bapparabi** [comment]
i have just run the config file . and it show the problem i am using this software 

https://github.com/sammy007/open-ethereum-pool

**Comment by NotoriousPyro** [comment]
That software is not compatible with ETP and you should only run a pool if you know how to program as it is not easy.

You're welcome to mine at metaverse.farm

**Comment by luozhaohui** [comment]
We have written a guide line for setting up a mining pool. Please refer to [How to setup a mining pool for ETP](https://docs.mvs.org/docs/setup_mining_pool.html).
