### ISSUE TITLE
Metaverse How to create a Raw transaction (tutorial).

### ISSUE THREAD

**Issue by sikamedia** [mvs-org/metaverse#213]
Please make a doc "How to create a raw transaction in Metaverse", example like https://www.youtube.com/embed/V48sANLy0Xc .

**Comment by betachen** [comment]
Hi @sikamedia ,
Dongyun has written commands doc, but not friendly.

<https://github.com/mvs-org/metaverse/wiki/Metaverse-API-Call-List#createrawtx>

**Comment by sikamedia** [comment]
Hi @betachen @wdyoschina 
As createrawtx command has Options  
`-i [--message]       Message/Information attached to this transaction `
How to verify the message in MVS?

**Comment by wdyoschina** [comment]
Hi sikamedia,
sorry for late response, the message verify way same with address verify. message is just content attached on address in our design.

**Comment by luozhaohui** [comment]
Document of rawtx API is here: https://docs.mvs.org/api_v2/rawtx.html
