### ISSUE TITLE
getmininginfo returns a poorly-formatted JSON response in v2.

### ISSUE THREAD

**Issue by NotoriousPyro** [mvs-org/metaverse#225]
In v1 API, the response was fine but could have been renamed from "mining-info" to "result":
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"getmininginfo","params":[],"id":1}' http://127.0.0.1:8820/rpc`
```
{
        "mining-info" :
        {
                "difficulty" : "9230099912566",
                "height" : "852401",
                "is-mining" : false,
                "rate" : "0"
        }
}
```
Now, in v2 this is a sub-object of "result" and causes headaches, is obtuse (as we already know we are asking for mining info) when trying to Unmarshal JSON:
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"getmininginfo","params":[],"id":1}' http://127.0.0.1:8820/rpc/v2`
```
{
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" :
        {
                "mining-info" :
                {
                        "difficulty" : "9212081176185",
                        "height" : "852403",
                        "is-mining" : false,
                        "rate" : "0"
                }
        }
}
```

Instead, the following should preferentially be returned:
```
{
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" :
        {
                "difficulty" : "9212081176185",
                "height" : "852403",
                "is-mining" : false,
                "rate" : "0"
        }
}
```

**Comment by jowenshaw** [comment]
For compatibility reasons with v1, we won't change this soon. There exists many of the same situations of the response result. It may be re-designed later.

**Comment by NotoriousPyro** [comment]
Why is the fact that a v2 request returns this because a v2 response would not be read by languages such as golang if it was written v1 in mind.

**Comment by NotoriousPyro** [comment]
The api should differentiate between v1 and v2 and return a different result.

**Comment by luozhaohui** [comment]
Fixed in APIv3 [getmininginfo](https://docs.mvs.org/zh-cn/api_v3/blockchain.html#getmininginfo)
