### ISSUE TITLE
verifyaddress returns a poorly-formatted JSON response in v2.

### ISSUE THREAD

**Issue by NotoriousPyro** [mvs-org/metaverse#226]
If you query a valid address:
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"validateaddress","params":["MBH5mtwPvNFqMqb6S9HN5hNCG5Wbu8WaCb"],"id":1}' http://127.0.0.1:8820/rpc/v2`
You  get the expected:
```
{
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" :
        {
                "address-type" : "p2kh(main-net)",
                "is-valid" : true,
                "message" : "valid address ",
                "test-net" : false
        }
}
```
Which is useful for when you're creating a struct like so:
```
type ValidateAddress struct {
	IsValid		bool		`json:"is-valid"`
	TestNet		bool		`json:"test-net"`
}
```
However, the struct becomes somewhat useless because of the response when you query an invalid address (as it doesn't just switch is-valid to false...):
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"validateaddress","params":["MBH5mtwPvNFqMqb6S9HN5hNCG5Wbu8WaCc"],"id":1}' http://127.0.0.1:8820/rpc/v2`
```
{
        "error" :
        {
                "code" : 1021,
                "message" : "the argument ('MBH5mtwPvNFqMqb6S9HN5hNCG5Wbu8WaCc') for option '--PAYMENT_ADDRESS' is invalid"
        },
        "id" : 1,
        "jsonrpc" : "2.0"
}
```

**Comment by jowenshaw** [comment]
fixed, now the response for invalid address is:
```bash
{
	"id" : 1,
	"jsonrpc" : "2.0",
	"result" : 
	{
		"address-type" : "none",
		"is-valid" : false,
		"message" : "invalid address!",
		"test-net" : true
	}
}
```
