### ISSUE TITLE
fetch-balance returns a poorly-formatted JSON response in v2.

### ISSUE THREAD

**Issue by NotoriousPyro** [mvs-org/metaverse#234]
_Similarly to #226 and #225_ 
When querying fetch-balance via v2, the objects are embedded within another object and causes increased complexity to interface with the API and increased chance to break by having to write extra decoding info.

`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"fetch-balance","params":["MBH5mtwPvNFqMqb6S9HN5hNCG5Wbu8WaCb"],"id":1}' http://127.0.0.1:8820/rpc/v2`
```
{
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" :
        {
                "balance" :
                {
                        "address" : "MBH5mtwPvNFqMqb6S9HN5hNCG5Wbu8WaCb",
                        "confirmed" : 354535699733,
                        "frozen" : 0,
                        "received" : 354535699733,
                        "unspent" : 354535699733
                }
        }
}

```

This is easier to work with:
```
{
        "id" : 1,
        "jsonrpc" : "2.0",
        "result" :
        {
                "address" : "MBH5mtwPvNFqMqb6S9HN5hNCG5Wbu8WaCb",
                "confirmed" : 354535699733,
                "frozen" : 0,
                "received" : 354535699733,
                "unspent" : 354535699733
        }
}

```

**Comment by betachen** [comment]
@NotoriousPyro Thanks a lot.
We can released a new version v3 for this, to fix these poorly-formatted.

**Comment by NotoriousPyro** [comment]
Hello @betachen,

The problem of releasing v3, is that v2 is already a broken implementation and doesn't do what it was intended to (for backwards compatibility) as v2 is not compatible with v1 responses.

I don't see any improvement in v2, just that the responses have now been placed in new objects.

**Comment by NotoriousPyro** [comment]
In fact, on my pool at metaverse.farm I use a combination of v2 and v1 calls because not all my v1 calls can be easily replaced by v2 without more work that I am unwilling to do (as it will break again, with v3)

**Comment by betachen** [comment]
Okay, combination v1 and v2 is useable, v3 will be release later, may 0.8.0。
v2 is finished, regarding to the v1 response is not developers friendly.
We will fix these poorly-formatted JSON issue in next API version.

**Comment by luozhaohui** [comment]
Fixed in APIv3 [getbalance](https://docs.mvs.org/zh-cn/api_v3/blockchain.html#getbalance)
