### ISSUE TITLE
MVS Wallet Export not working + 'Import From File' on account creation is not working

### ISSUE THREAD

**Issue by Joske2** [mvs-org/metaverse#240]
-When creating a new account on MVS wallet the 'import from file' does not work (can't checkmarkt it).  (Osx high Sierra, Chrome).

-When in wallet and go to 'advanced' the export Wallet is 'not available'!

- You have a guide in how to use QR to connect to phone but that does not work!! When scanning the QR it give you a 'barcode' fill box. http://tinypic.com/r/jjtgkl/9

-Question: How can one get the private keys from the Console? What is the right 'string'

**Comment by luozhaohui** [comment]
You do not need to get the private keys, you should backup your mnemonic words by cli-cmd 'getaccount' or 'dumpkeyfile'.

Please refer to [Getting started with mobile](https://docs.mvs.org/docs/mobile.html)
