### ISSUE TITLE
Desktop, click metaverse icon will not pop up browser.

### ISSUE THREAD

**Issue by betachen** [mvs-org/metaverse#242]
### Windows
when double-click icon, will not pop-pup browser, but tray runs successfully. Then exit, double-click second time, then pop-up browser, but tray/mvsd not runs.

### Mac
When you install new version 0.7.3, can't find out the startup icon of metaverse. you have to install again.

**Comment by yangguanglu** [comment]
for Windows it will be fixed on version 0.7.4.
for Mac it not always occurs,it will be fixed it when it happened again.
