### ISSUE TITLE
The latest wallet does not return information about the current mineable block

### ISSUE THREAD

**Issue by NotoriousPyro** [mvs-org/metaverse#253]
In the older versions of the wallet, one could simply use `fetchheaderext` and issue `pending` in the parameters.

This has been removed in the latest versions has been 'obliterated' and now I must use `getmininginfo` which instead of returning the "pending" block information returns the current block that was just mined... I now have to use the following to get the correct height:
`height = height+1`

Why was this change implemented?

**Comment by betachen** [comment]
sorry about that, we checked it, missing parameter in new command.
will add fetchheaderext and release patch within this week.

**Comment by NotoriousPyro** [comment]
Resolved in latest main.
