### ISSUE TITLE
fetch-balance crashes the very latest wallet that was just pushed to the master branch

### ISSUE THREAD

**Issue by NotoriousPyro** [mvs-org/metaverse#256]
Through testing out all the commands before rolling this out to metaverse.farm, I have found that if you issue RPC with fetch-balance, the wallet stops responding and does not respond until restarted:
```
root@ip-172-31-12-248:/opt/metaverse/build# curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"fetch-balance","params":["MB6MeDUxGUHR5f7XygMhrsoTbf3QduweRu"],"id":1}' http://127.0.0.1:8820/rpc/v2
[Cursor blinking]
```

```
root@ip-172-31-12-248:/opt/metaverse/build# mvs-cli
[Cursor blinking]
```

After a few seconds, trying again:
```
root@ip-172-31-12-248:/opt/metaverse/build# mvs-cli
connect[127.0.0.1:8820/rpc/v2] failed: Connection refused
```

```
root@ip-172-31-12-248:/opt/metaverse/build# curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"fetch-balance","params":["MB6MeDUxGUHR5f7XygMhrsoTbf3QduweRu"],"id":1}' http://127.0.0.1:8820/rpc/v2
curl: (7) Failed to connect to 127.0.0.1 port 8820: Connection refused
```
The process has now stopped and must be restarted:
```
root@ip-172-31-12-248:/opt/metaverse/build# systemctl restart mvsd
root@ip-172-31-12-248:/opt/metaverse/build# mvs-cli
[Output of MVSD commands]
```

**Comment by NotoriousPyro** [comment]
This started working again shortly after, but seemed to crash intermittently. Can this please be investigated to see if this issue can be replicated?

**Comment by betachen** [comment]
Thanks, we will check it soon.

**Comment by betachen** [comment]
In all probability, I think would be too many outputs take so much time.
Anyway, we should check at first.

**Comment by betachen** [comment]
I test this API in my host.
Linux E5-2682/4Core/8GB  takes 7 seconds, then got response
Windows i7/4Core/12GB takes 5 secondrs, then got response.

can you test it, and wait for more seconds

**Comment by NotoriousPyro** [comment]
Yes, it works - but first few times the wallet crashed. The wallet should stay stable and not crash.

**Comment by NotoriousPyro** [comment]
Will reopen if needed.
