### ISSUE TITLE
Cpchain partner

### ISSUE THREAD

**Issue by DiplomaticImmunity** [mvs-org/metaverse#266]
Hello, you forgot to list Cpchain as a partner on https://mvs.org/

https://medium.com/@mvs_org/metaverse-and-cpchain-to-collaborate-on-r-d-and-promotion-of-blockchain-architecture-a5b0352af8fc

**Comment by NotoriousPyro** [comment]
As per my comment in #267 this would probably be better posted in https://github.com/mvs-org/mvs-live/issues which is for the Website. This repository is for the full C++ wallet.

**Comment by betachen** [comment]
@NotoriousPyro Thanks.

@DiplomaticImmunity  have done. then close.
