### ISSUE TITLE
Suggestion for team

### ISSUE THREAD

**Issue by DiplomaticImmunity** [mvs-org/metaverse#267]
Hello, I have a suggestion for your website https://mvs.org/  If you can specify for each team member their profession and link their Linkedin profile. like this https://aion.network/team.html

And add other team members, like the new marketing team? Atina and other people who works on metaverse.

thanks

**Comment by NotoriousPyro** [comment]
This would probably be better posted in https://github.com/mvs-org/mvs-live/issues
