### ISSUE TITLE
Let getwork/submitwork  same as ETH interface.

### ISSUE THREAD

**Issue by betachen** [mvs-org/metaverse#268]
Let getwork/submitwork  same as ETH interface.
Then MVS can share ETH pool as well.

**Comment by chengzhpchn** [comment]
1. make alias for command getwork/submitwork as eth_getWork/eth_submitWork;
2. the new rpc interface corresponding to url: "http://127.0.0.1:8820/rpc/_**v3**_";
3. refer to eth_submitWork JSON API introduction: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_submitwork, Note: the Nonce parameter is started with "**_0x_**", which is different with the original MVS submitwork API.

the testcase is also added in:
test/test-rpc/online_testcase/test_work.py

**Comment by chengzhpchn** [comment]
this feature has been published with Super Nova
