### ISSUE TITLE
Critical vulnerability in difficulty retarget algo

### ISSUE THREAD

**Issue by xiphon** [mvs-org/metaverse#274]
Hello, i'm running FairPool ETP mining pool https://etp.fairpool.xyz.
15 Mar 2018 i've noticed some strange activity on the blockchain.

This looks like a critical flaw in the ETP difficulty retarget algo:

Is possible to lower the diff below the real expected value, supplying the blockchain with the blocks with altered timestamp set to
`previous block timestamp + 24 sec`

https://github.com/mvs-org/metaverse/blob/master/src/lib/blockchain/validate_block.cpp#L301
```c++
bool validate_block::is_valid_time_stamp(uint32_t timestamp) const
{ 
    // Use system clock because we require accurate time of day.
    typedef std::chrono::system_clock wall_clock;
    const auto block_time = wall_clock::from_time_t(timestamp);
    const auto two_hour_future = wall_clock::now() + time_stamp_window;
    return block_time <= two_hour_future;
}
```

https://github.com/mvs-org/metaverse/blob/master/src/lib/consensus/common/libdevcore/BasicType.cpp#L148
```c++
    static uint32_t time_config{24};
...
    if(_bi.timestamp >= _parent.timestamp + time_config)
    {
		target = _parent.bits - (_parent.bits/1024);
```

**Comment by aleqx** [comment]
Are blocks then being orphaned?

**Comment by betachen** [comment]
https://github.com/mvs-org/metaverse/commit/5c10ed0baaafbd1d63f7a8d6c772936eab90069a

**Comment by betachen** [comment]
see <https://docs.mvs.org/news/>
