### ISSUE TITLE
[consensus] store_block error_code: 30

### ISSUE THREAD

**Issue by baaa** [mvs-org/metaverse#283]
Hi, I have created a custom testnet with (wallet version 0.7.5)
```
[network]
identifier = 1234567899
```

mined 3 blocks with the wallets "cpu mining" feature. (wallet crashes after finding every block, but this is not the issue I am writing about)

now mining block number 4, I am using an external miner, here is some info:
```
getmininginfo
{
	"mining-info" : 
	{
		"difficulty" : "300,000",
		"height" : "3",
		"is-mining" : false,
		"rate" : "0"
	}
}

getwork
{
	"result" : 
	[
		"0x29d64190193fdb22313a54b37a361d3f4d24eb98694656a871811958d695e2da",
		"0x0000000000000000000000000000000000000000000000000000000000000000",
		"0x000037ec8ec25e6d2c0bafefd59ebbd0b471449f24ac401db5abd74229ff6635"
	]
}
```

miner finds the following share coming through eth_submitWork
```{"worker":"zoo","id":4,"method":"eth_submitWork","params":["0x1bdbfe2005866f7f","0x717b8706fe39a0a9dab264742168bd91f9d16c3cbe01a418b0f3768a343d809a","0x5b21ecf35f2fcf63679972cb9523f07de5d01cf3d7e8415db617c05896d3eeee"]}```

I apply the following transformations to submitted nonce value:
1- remove 0x and convert it to BigInteger
2- XOR the result with 0x6675636b6d657461
3- convert it to a hex representation
with the following code
```
    val n1 = hexToBig(nonce.stripPrefix("0x"))
    val n2 = n1 ^ hexToBig("6675636b6d657461")
    val n3 = n2.toString(16)
    log.info(s"nonce:$nonce n1: $n1 n2: $n2, n3:$n3")
```

the log line here prints the result as:

```
[02/Apr/2018:15:46:07 BST] INFO  [RPC] - nonce:0x1bdbfe2005866f7f n1: 2007477472408792959 n2: 9056348847896468254, n3:7dae9d4b68e31b1e
```

I checked these calculations with external tools they all seem to be correct.
Then I use json rpc to submit work with the following payload:

```
{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"submitwork",
  "params":["0x7dae9d4b68e31b1e","0x717b8706fe39a0a9dab264742168bd91f9d16c3cbe01a418b0f3768a343d809a","0x5b21ecf35f2fcf63679972cb9523f07de5d01cf3d7e8415db617c05896d3eeee"]
}
```

The block gets rejected and in the wallet log I only see this message:
```20180402T154607 ERROR [etp_hash] 4 block  verified failed !

20180402T154607 ERROR [consensus] store_block error_code: 30
```

Can you tell me what error_code 30 is? and if I am missing something obvious? The above submitted share has a difficulty higher than 1G, am I missing some conversion somewhere?

**Comment by betachen** [comment]
Add error text decription for each error_code in log please;
then give the error_code 30 description here.
@chengzhpchn

**Comment by chengzhpchn** [comment]
error_code 30 means:
**_proof of work failed_**

For more details abour error_code, please refer to: error.hpp and error.cpp.

**Comment by baaa** [comment]
@chengzhpchn but the proof of work for the data I have shown is correct (you can check this)
so the real question is why would I get this error. @canguruhh on discord mentioned he used to get this error on testnet "sometimes" but unable to produce this consistently, and restarting the wallet solved his issues.

I am getting this error consistently and provide you with any data you wish if you want to investigate.

I will tonight use a wallet with the supernova fork and see if this issue persists on testnet.

**Comment by baaa** [comment]
@chengzhpchn @betachen I finally managed to get the wallet to accept blocks on supernova wallet (0.8.0) 
You might want to update the documentation to note that rpc expects nonce to NOT have have `0x` but mix digest and header hash values REQUIRE `0x`

for example you got to submit the block like 
```
{
  "jsonrpc":"2.0",
  "id":"1",
  "method":"submitwork",
  "params":["7dae9d4b68e31b1e","0x717b8706fe39a0a9dab264742168bd91f9d16c3cbe01a418b0f3768a343d809a","0x5b21ecf35f2fcf63679972cb9523f07de5d01cf3d7e8415db617c05896d3eeee"]
}```

submitting the nonce as `0x7dae9d4b68e31b1e` fails.

**Comment by baaa** [comment]
you may close this issue but I highly recommend updating documentation on https://docs.mvs.org/api_v2/blockchain.html#submitwork

**Comment by jowenshaw** [comment]
@baaa   Thank you very much!
https://github.com/mvs-org/docs-mvs-org/pull/2 was merged.
