### ISSUE TITLE
Error while refreshing pending block on main

### ISSUE THREAD

**Issue by nixtechie49** [mvs-org/metaverse#288]
System information
Metaverse version : 0.7.5

Redis version: redis-server --version

Redis server v=4.0.9
OS & Version: Linux/OSX
Ubuntu 16.04

Commit branch and hash: (master, ba60e1c)

Expected behavior
./build/bin/open-ethereum-pool config.json
When running this command pool needed to start. But error arose.

Actual behavior
Getting Error

Error while refreshing pending block on main: json: cannot unmarshal string into Go struct field JSONRpcResp.error of type map[string]interface {}

Can anybody help, please?

**Comment by NotoriousPyro** [comment]
This isn't ethereum. Open-ethereum-pool won't work without modifications. You need programming knowledge to do it.

**Comment by luozhaohui** [comment]
Ref:
[https://github.com/mvs-org/docs-mvs-org/tree/master/.appendix/mining_pool_setup](https://github.com/mvs-org/docs-mvs-org/tree/master/.appendix/mining_pool_setup)
