### ISSUE TITLE
Metaverse icon doesn't show up in the menu bar for Macos

### ISSUE THREAD

**Issue by peter-fu** [mvs-org/metaverse#289]
**MacOS version**

macOS Sierra
Version 10.12.6

**Walle version**

mvs-macOSX-x86_64-v0.7.5.pkg

![qq20180507-074508](https://user-images.githubusercontent.com/930535/39679058-9fcd35e8-51ca-11e8-9860-05ae568e8cb1.png)

**Comment by yangguanglu** [comment]
@peter-fu yes,the main program is running in the background ,there should be a tray icon.If the icon does not appear, please kill the process of Metaverse and restart it again.

**Comment by peter-fu** [comment]
Thanks, but I tried all the following which didn't work (the tray icon doesn't show up).

- Restart the process
- Restart MacOS
- Reinstall the wallet

I used to have mvs-macOSX-x86_64-v0.6.9 on this MacBook, not sure whether that's related. It does work in Windows as always.

**Comment by yangguanglu** [comment]
@peter-fu can you type in the terminal "mvsd" to start the main process?And to see if it is 0.7.5 or other versions.

**Comment by yangguanglu** [comment]
@peter-fu at first, kill the process of mvsd and Metaverse.

**Comment by peter-fu** [comment]
Problem solved. Thanks a lot.

Caused identified as: I used to have mvs-macOSX-x86_64-v0.6.9 on this MacBook.

**Detailes below**

I tried the mvsd command, and it shows some errors.

```
peter.fu@mbp:MacOS$ ./mvsd
20180508T225346 INFO [server] mvsd version 0.7.5
20180508T225346 INFO [server] ================= startup ==================
20180508T225346 ERROR [server] ================= startup ==================
20180508T225346 FATAL [server] ================= startup ==================
20180508T225346 INFO [server] Using config file: "/Users/peter.fu/Library/Application Support/Metaverse"
20180508T225346 INFO [server] Please wait while the server is starting...
20180508T225346 ERROR [node] Blockchain failed to start.
20180508T225346 ERROR [server] Server failed to start with error, operation failed.
20180508T225346 INFO [server] Please wait while the server is stopping...
20180508T225346 INFO [node] Server stopped successfully.
```

By removing the whole folder of "/Users/peter.fu/Library/Application Support/Metaverse", everything starts to work again.

**Comment by peter-fu** [comment]
After I removed the `/Users/peter.fu/Library/Application Support/Metaverse` folder, the mvsd process could start successfully and it started to sync. However, the wallet doesn't show up in browser (see attachment below).

![qq20180508-231010](https://user-images.githubusercontent.com/930535/39765792-3f36a9a2-5315-11e8-892d-c8cf67677451.png)

Reinstalling the 0.7.5 wallet fixed that.

**Comment by peter-fu** [comment]
Full steps to resolve the problems.

1. Remove the `/Users/peter.fu/Library/Application Support/Metaverse` folder
2. Remove the 0.7.5 wallet application
3. Install the 0.7.5 wallet application again
