### ISSUE TITLE
Cannot create Metaverse Smart Token

### ISSUE THREAD

**Issue by claudesu520** [mvs-org/metaverse#296]
[Issue]
When I create Metaverse Smart Token in testnet, it return a error that:
"Impossible to create this asset. Symbol FRANK.TOKEN is forbidden."

[Environment]
Testnet

[Version]
0.8.0

[Attachment]
![image](https://user-images.githubusercontent.com/38309121/40971501-718f188a-68f0-11e8-8604-68315b32cab2.png)

**Comment by CaptainStevey** [comment]
Looks like you can't create [name].TOKEN at all

**Comment by luozhaohui** [comment]
‘TOKEN’ is not allowed to appear in symbol.
