### ISSUE TITLE
Request: New call to get current owner and content of a MIT

### ISSUE THREAD

**Issue by CaptainStevey** [mvs-org/metaverse#297]
Is it worth creating a new call, getmitcurrent ?  

Right now we can:
use getmit [token] to get the content and the original issue DID.  
use getmit [token] -t to get the transaction history and current owner (first result).

If there was a getmitcurrent it would prevent having to make two calls to get the current owner and content of a token.   

Else if we were to add content to the -t call then it would return a lot of extra detail so perhaps not the better of the two ideas.

getmit BIAM.KRIS
{
	"address" : "tUHgqqwUx1tgjAQunnwSEmZAKPhhQV9gNX",
	**"content" : "Kris_is_the_best",**
	"height" : 453683,
	"status" : "registered",
	"symbol" : "BIAM.KRIS",
	"time_stamp" : 1528277598,
	"to_did" : "BIAMKING"
}
getmit BIAM.KRIS -t
{
	"mits" : 
	[
		{
			"address" : "t7yBZL47cWMVjGHqq1Y3JcZX1wpmNRUkvU",
			"height" : 453689,
			"status" : "transfered",
			"symbol" : "BIAM.KRIS",
			"time_stamp" : 1528278331,
			**"to_did" : "Google"**
		},
		{
			"address" : "tUHgqqwUx1tgjAQunnwSEmZAKPhhQV9gNX",
			"height" : 453683,
			"status" : "registered",
			"symbol" : "BIAM.KRIS",
			"time_stamp" : 1528277598,
			"to_did" : "BIAMKING"
		}
	]
}

**Comment by luozhaohui** [comment]
We have added a option "--current" to "getmit" for your proposal.  This feature will be released in version0.8.1.

Example:
`
$ ./mvs-cli getmit Alice@MIT -c
{
	"address" : "MJevGQHGwKQGNpeJF1vDxBawxKoRZMqsRz",
	"content" : "Alice's MIT",
	"height" : 7090,
	"status" : "transfered",
	"symbol" : "Alice@MIT",
	"time_stamp" : 1528183391,
	"to_did" : "Bob"
}
`

**Comment by luozhaohui** [comment]
The latest version has released this feature.
