### ISSUE TITLE
[Request]Disable mvsd aggressive network scan

### ISSUE THREAD

**Issue by luozhaohui** [mvs-org/metaverse#310]
Miner want to disable mvsd aggressive network scan because their sever providers claim about scan on 5251 port like this:
![claims ](https://i.imgur.com/RicShmL.png)

**Comment by chengzhpchn** [comment]
[network]
# The number of concurrent attempts to establish one connection, defaults to 5.
connect_batch_size = 5

This configuration parameter "connect_batch_size" is used to control "The number of concurrent attempts to establish one connection". And the default value "5", will make at most 5 attempts to establish the connection. Of cource, if the previous 3 attempts were success, no more attempts will be performed.

So try to decrease the value of "connect_batch_size" to 1 or 2, maybe this will help to decrease the aggressive network scan to be more friendly.
