### ISSUE TITLE
[bug]BTC-p2p manager does not work on MVS network.

### ISSUE THREAD

**Issue by luozhaohui** [mvs-org/metaverse#312]
BTC-p2p manager does not work on MVS network.

Ref:
[BTC-p2p manager](https://github.com/cryptocoinjs/btc-p2p)

**Comment by canguruhh** [comment]
seems like something is wrong with the version ack. i cannot get the ack message

**Comment by canguruhh** [comment]
we now have the [metaversejs-p2p](https://github.com/mvs-org/metaversejs-p2p) library for p2p layer communication
