### ISSUE TITLE
Ubuntu 17.10 compile errors.

### ISSUE THREAD

**Issue by Serpent6877** [mvs-org/metaverse#316]
Latest git. Everything else compiled fine.

[  1%] Building C object include/metaverse/consensus/libethash/CMakeFiles/ethash.dir/internal.c.o
cd /usr/src/metaverse/build/include/metaverse/consensus/libethash && /usr/bin/cc  -I/usr/src/metaverse/contrib -I/usr/src/metaverse/include -I/usr/local/include  -std=c11 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -std=gnu99 -O3 -DNDEBUG   -o CMakeFiles/ethash.dir/internal.c.o   -c /usr/src/metaverse/include/metaverse/consensus/libethash/internal.c
/usr/src/metaverse/include/metaverse/consensus/libethash/internal.c: In function ‘ethash_full_new_internal’:
/usr/src/metaverse/include/metaverse/consensus/libethash/internal.c:472:12: error: this statement may fall through [-Werror=implicit-fallthrough=]
         if (ethash_io_prepare(dirname, seed_hash, &f, (size_t)full_size, true) != ETHASH_IO_MEMO_MISMATCH) {
            ^
/usr/src/metaverse/include/metaverse/consensus/libethash/internal.c:477:5: note: here
     case ETHASH_IO_MEMO_MISMATCH:
     ^~~~
/usr/src/metaverse/include/metaverse/consensus/libethash/internal.c: In function ‘ethash_light_compute_internal’:
/usr/src/metaverse/include/metaverse/consensus/libethash/internal.c:252:39: error: ‘tmp_node’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                     mix[n].words[w] = fnv_hash(mix[n].words[w], dag_node->words[w]);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/metaverse/include/metaverse/consensus/libethash/internal.c:252:39: error: ‘*((void *)&tmp_node+16)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/usr/src/metaverse/include/metaverse/consensus/libethash/internal.c:252:39: error: ‘*((void *)&tmp_node+32)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/usr/src/metaverse/include/metaverse/consensus/libethash/internal.c:252:39: error: ‘*((void *)&tmp_node+48)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
[  1%] Building CXX object contrib/cryptojs/CMakeFiles/cryptojs_static.dir/cryptojs_impl.cpp.o
cd /usr/src/metaverse/build/contrib/cryptojs && /usr/bin/c++   -I/usr/src/metaverse/contrib -I/usr/src/metaverse/include -I/usr/local/include  -std=c++14 -fstrict-aliasing -fvisibility=hidden -Wall -Wextra -Wstrict-aliasing=2 -Wno-unused-parameter -Wno-unused-variable -Wno-type-limits -Werror -pthread -fno-enforce-eh-specs -fnothrow-opt -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-but-set-parameter -O3 -DNDEBUG   -o CMakeFiles/cryptojs_static.dir/cryptojs_impl.cpp.o -c /usr/src/metaverse/contrib/cryptojs/cryptojs_impl.cpp
cc1: all warnings being treated as errors
include/metaverse/consensus/libethash/CMakeFiles/ethash.dir/build.make:89: recipe for target 'include/metaverse/consensus/libethash/CMakeFiles/ethash.dir/internal.c.o' failed

Any direction on this?

**Comment by Serpent6877** [comment]
Possible same issue due to new GCC?

https://github.com/ethereum/solidity/issues/2420

**Comment by luozhaohui** [comment]
Thanks. That's the problem, we'll fix it in the next release.

**Comment by luozhaohui** [comment]
Fix in [v0.8.2](https://github.com/mvs-org/metaverse/releases/tag/v0.8.2)
