### ISSUE TITLE
Compress message in attachment.

### ISSUE THREAD

**Issue by luozhaohui** [mvs-org/metaverse#320]
The maximum of message length is 256. Maybe we needs compress message in attachment.
Ref: MTP, MMS, BSON, base64.

**Comment by chengzhpchn** [comment]
Compress software: -- xz(xz-5.2.3)
Compress content: LICENSE file in metaverse github.
Test procedure:
1. split LICENSE file into segments
2. compress each segments and caculate the compress radio
3. draw the data.

[Imgur](https://i.imgur.com/tzceSV6.png)

as the picture shows:
1. when the file size is 200 bytes, the compress ratio is 100%;
2. when the file size is 400 bytes, the compress ratio is 80%;
3. when the file size is 600 bytes, the compress ratio is 65%;
4. when the file size is 800 bytes, the compress ratio is 60%;

It is very hard too get a high compress ratio for a small file counts in bytes.
