### ISSUE TITLE
Segmentation fault with v0.8.5 on testnet

### ISSUE THREAD

**Issue by dhkstn** [mvs-org/metaverse#338]
Segmentation fault occurs with v0.8.5 on testnet.
Please refer the below logs.
--------------------------------------------------------------------------------------------------------
20181227T045137 INFO [blockchain]  PoW block [939814] verified in (0) secs or (0) ms/input
20181227T045155 INFO [blockchain]  PoW block [939815] verify (1) txs and (1) inputs
20181227T045155 INFO [blockchain]  PoW block [939815] verified in (0) secs or (0) ms/input
20181227T045220 INFO [blockchain]  PoW block [939816] verify (1) txs and (1) inputs
20181227T045220 INFO [blockchain]  PoW block [939816] verified in (0) secs or (0) ms/input
20181227T045229 INFO [blockchain]  PoW block [939817] verify (1) txs and (1) inputs
20181227T045229 INFO [blockchain]  PoW block [939817] verified in (0) secs or (0) ms/input
Segmentation fault
--------------------------------------------------------------------------------------------------------

I just run the metaverse ETP daemon with command(./mvsd -t).
Could you please check this?

**Comment by dhkstn** [comment]
I can't see this issue when I use the v0.8.4.

**Comment by dhkstn** [comment]
any update on this?

**Comment by luozhaohui** [comment]
I can not reproduce the problem.
Did you kill mvsd process before you restart? 
Please run follow command to check:
`ps -ef | grep mvs`

**Comment by dhkstn** [comment]
here is full log for reproducing this issue.
the issue occurs about 1hour later after launching the mvsd daemon.

-------------------------------------------------------------------------------------------
[coin@localhost v0.8.5]$
[coin@localhost v0.8.5]$ ps -ef | grep mvsd
coin      4685  1574  0 00:45 pts/0    00:00:00 grep --color=auto mvsd
[coin@localhost v0.8.5]$
[coin@localhost v0.8.5]$
[coin@localhost v0.8.5]$ ./mvsd -t
20190107T004550 INFO [server] mvsd version 0.8.5
20190107T004550 INFO [server] ================= startup ==================
20190107T004550 ERROR [server] ================= startup ==================
20190107T004550 FATAL [server] ================= startup ==================
20190107T004550 INFO [server] Using config file: "/home/coin/.metaverse/mvs-test.conf"
20190107T004550 INFO [server] Please wait while the server is starting...
20190107T004550 INFO [server] running testnet
20190107T004550 INFO [node] Starting manual session.
20190107T004550 INFO [http] Http Service listen on 0.0.0.0:8820
20190107T004550 INFO [MONGO] Websocket Service listen on 127.0.0.1:8821
20190107T004550 INFO [network] Contacting seed [test-asia.metaverse.live:15251]
20190107T004550 INFO [network] Contacting seed [test-americas.metaverse.live:15251]
20190107T004550 INFO [network] Contacting seed [test-europe.metaverse.live:15251]
20190107T004550 INFO [network] Contacting seed [test-asia.mvs.live:15251]
20190107T004550 INFO [network] Contacting seed [test-americas.mvs.live:15251]
20190107T004550 INFO [network] Contacting seed [test-europe.mvs.live:15251]
20190107T004551 INFO [network] Connected seed [test-asia.mvs.live:15251] as 118.178.16.25:15251
20190107T004551 INFO [network] Seed channel stopped: channel is stopped
20190107T004551 INFO [network] Connected seed [test-americas.mvs.live:15251] as 104.131.154.21:15251
20190107T004552 INFO [network] Failure contacting seed [test-asia.metaverse.live:15251] operation failed
20190107T004552 INFO [network] Seed channel stopped: channel is stopped
20190107T004556 INFO [network] Failure contacting seed [test-americas.metaverse.live:15251] connection timed out
20190107T004556 INFO [network] Failure contacting seed [test-europe.metaverse.live:15251] connection timed out
20190107T004556 INFO [network] Failure contacting seed [test-europe.mvs.live:15251] connection timed out
20190107T004556 INFO [server] Seeding is complete.
20190107T004556 INFO [network] session_seed complete!
20190107T004557 INFO [node] Node start height is (967586).
20190107T004557 INFO [node] Starting inbound session.
20190107T004557 INFO [node] Starting outbound session.
20190107T004557 INFO [server] Bound public query service to tcp://*:9091
20190107T004557 INFO [server] Server is started.
20190107T004558 INFO [blockchain]  PoW block [967587] verify (1) txs and (1) inputs
20190107T004559 INFO [blockchain]  PoW block [967587] verified in (0.053) secs or (53) ms/input
20190107T004559 INFO [blockchain]  PoW block [967588] verify (1) txs and (1) inputs
20190107T004559 INFO [blockchain]  PoW block [967588] verified in (0) secs or (0) ms/input
20190107T004603 INFO [blockchain]  PoW block [967589] verify (1) txs and (1) inputs
20190107T004603 INFO [blockchain]  PoW block [967589] verified in (0) secs or (0) ms/input
20190107T004650 INFO [blockchain]  PoW block [967590] verify (1) txs and (1) inputs
20190107T004650 INFO [blockchain]  PoW block [967590] verified in (0) secs or (0) ms/input
20190107T004725 INFO [blockchain]  PoW block [967591] verify (1) txs and (1) inputs
20190107T004725 INFO [blockchain]  PoW block [967591] verified in (0) secs or (0) ms/input
20190107T004727 INFO [blockchain]  PoW block [967592] verify (1) txs and (1) inputs
20190107T004727 INFO [blockchain]  PoW block [967592] verified in (0) secs or (0) ms/input
20190107T004731 INFO [blockchain]  PoW block [967593] verify (1) txs and (1) inputs
20190107T004731 INFO [blockchain]  PoW block [967593] verified in (0) secs or (0) ms/input
20190107T004743 INFO [blockchain]  PoW block [967594] verify (1) txs and (1) inputs
20190107T004743 INFO [blockchain]  PoW block [967594] verified in (0) secs or (0) ms/input
20190107T004806 INFO [blockchain]  PoW block [967595] verify (1) txs and (1) inputs
20190107T004806 INFO [blockchain]  PoW block [967595] verified in (0) secs or (0) ms/input
20190107T004814 INFO [blockchain]  PoW block [967596] verify (1) txs and (1) inputs
20190107T004814 INFO [blockchain]  PoW block [967596] verified in (0) secs or (0) ms/input
20190107T004814 INFO [blockchain]  PoW block [967597] verify (1) txs and (1) inputs
20190107T004814 INFO [blockchain]  PoW block [967597] verified in (0) secs or (0) ms/input
20190107T004842 INFO [blockchain]  PoW block [967598] verify (1) txs and (1) inputs
20190107T004842 INFO [blockchain]  PoW block [967598] verified in (0) secs or (0) ms/input
20190107T004842 INFO [blockchain]  PoW block [967599] verify (1) txs and (1) inputs
20190107T004842 INFO [blockchain]  PoW block [967599] verified in (0) secs or (0) ms/input
20190107T005009 INFO [blockchain]  PoW block [967600] verify (1) txs and (1) inputs
20190107T005009 INFO [blockchain]  PoW block [967600] verified in (0) secs or (0) ms/input
20190107T005046 INFO [blockchain]  PoW block [967601] verify (1) txs and (1) inputs
20190107T005046 INFO [blockchain]  PoW block [967601] verified in (0) secs or (0) ms/input
20190107T005200 INFO [blockchain]  PoW block [967602] verify (1) txs and (1) inputs
20190107T005203 INFO [blockchain]  PoW block [967602] verified in (3.119) secs or (3119) ms/input
20190107T005307 INFO [blockchain]  PoW block [967603] verify (1) txs and (1) inputs
20190107T005307 INFO [blockchain]  PoW block [967603] verified in (0) secs or (0) ms/input
20190107T005322 INFO [blockchain]  PoW block [967604] verify (1) txs and (1) inputs
20190107T005322 INFO [blockchain]  PoW block [967604] verified in (0) secs or (0) ms/input
20190107T005344 INFO [blockchain]  PoW block [967605] verify (1) txs and (1) inputs
20190107T005344 INFO [blockchain]  PoW block [967605] verified in (0) secs or (0) ms/input
20190107T005348 INFO [blockchain]  PoW block [967606] verify (1) txs and (1) inputs
20190107T005348 INFO [blockchain]  PoW block [967606] verified in (0) secs or (0) ms/input
20190107T005352 INFO [blockchain]  PoW block [967607] verify (1) txs and (1) inputs
20190107T005352 INFO [blockchain]  PoW block [967607] verified in (0) secs or (0) ms/input
20190107T005447 INFO [blockchain]  PoW block [967608] verify (1) txs and (1) inputs
20190107T005447 INFO [blockchain]  PoW block [967608] verified in (0) secs or (0) ms/input
20190107T005457 INFO [blockchain]  PoW block [967609] verify (1) txs and (1) inputs
20190107T005457 INFO [blockchain]  PoW block [967609] verified in (0) secs or (0) ms/input
20190107T005502 INFO [blockchain]  PoW block [967610] verify (1) txs and (1) inputs
20190107T005502 INFO [blockchain]  PoW block [967610] verified in (0) secs or (0) ms/input
20190107T005505 INFO [blockchain]  PoW block [967611] verify (1) txs and (1) inputs
20190107T005505 INFO [blockchain]  PoW block [967611] verified in (0) secs or (0) ms/input
20190107T005524 INFO [blockchain]  PoW block [967612] verify (1) txs and (1) inputs
20190107T005524 INFO [blockchain]  PoW block [967612] verified in (0) secs or (0) ms/input
20190107T005620 INFO [blockchain]  PoW block [967613] verify (1) txs and (1) inputs
20190107T005620 INFO [blockchain]  PoW block [967613] verified in (0) secs or (0) ms/input
20190107T005641 INFO [blockchain]  PoW block [967614] verify (1) txs and (1) inputs
20190107T005641 INFO [blockchain]  PoW block [967614] verified in (0) secs or (0) ms/input
20190107T005804 INFO [blockchain]  PoW block [967615] verify (1) txs and (1) inputs
20190107T005804 INFO [blockchain]  PoW block [967615] verified in (0.022) secs or (22) ms/input
20190107T005826 INFO [blockchain]  PoW block [967616] verify (1) txs and (1) inputs
20190107T005826 INFO [blockchain]  PoW block [967616] verified in (0.027) secs or (27) ms/input
20190107T005843 INFO [blockchain]  PoW block [967617] verify (1) txs and (1) inputs
20190107T005843 INFO [blockchain]  PoW block [967617] verified in (0) secs or (0) ms/input
20190107T005933 INFO [blockchain]  PoW block [967618] verify (1) txs and (1) inputs
20190107T005933 INFO [blockchain]  PoW block [967618] verified in (0) secs or (0) ms/input
20190107T005941 INFO [blockchain]  PoW block [967619] verify (1) txs and (1) inputs
20190107T005941 INFO [blockchain]  PoW block [967619] verified in (0) secs or (0) ms/input
20190107T010030 INFO [blockchain]  PoW block [967620] verify (1) txs and (1) inputs
20190107T010030 INFO [blockchain]  PoW block [967620] verified in (0) secs or (0) ms/input
20190107T010035 INFO [blockchain]  PoW block [967621] verify (1) txs and (1) inputs
20190107T010035 INFO [blockchain]  PoW block [967621] verified in (0) secs or (0) ms/input
20190107T010048 INFO [blockchain]  PoW block [967622] verify (1) txs and (1) inputs
20190107T010048 INFO [blockchain]  PoW block [967622] verified in (0) secs or (0) ms/input
20190107T010055 INFO [blockchain]  PoW block [967623] verify (1) txs and (1) inputs
20190107T010055 INFO [blockchain]  PoW block [967623] verified in (0) secs or (0) ms/input
20190107T010130 INFO [blockchain]  PoW block [967624] verify (1) txs and (1) inputs
20190107T010130 INFO [blockchain]  PoW block [967624] verified in (0) secs or (0) ms/input
20190107T010136 INFO [blockchain]  PoW block [967625] verify (1) txs and (1) inputs
20190107T010136 INFO [blockchain]  PoW block [967625] verified in (0) secs or (0) ms/input
20190107T010256 INFO [blockchain]  PoW block [967626] verify (1) txs and (1) inputs
20190107T010256 INFO [blockchain]  PoW block [967626] verified in (0) secs or (0) ms/input
20190107T010401 INFO [blockchain]  PoW block [967627] verify (1) txs and (1) inputs
20190107T010401 INFO [blockchain]  PoW block [967627] verified in (0) secs or (0) ms/input
20190107T010414 INFO [blockchain]  PoW block [967628] verify (1) txs and (1) inputs
20190107T010414 INFO [blockchain]  PoW block [967628] verified in (0) secs or (0) ms/input
20190107T010518 INFO [blockchain]  PoW block [967629] verify (1) txs and (1) inputs
20190107T010518 INFO [blockchain]  PoW block [967629] verified in (0) secs or (0) ms/input
20190107T010524 INFO [blockchain]  PoW block [967630] verify (1) txs and (1) inputs
20190107T010524 INFO [blockchain]  PoW block [967630] verified in (0) secs or (0) ms/input
20190107T010553 INFO [blockchain]  PoW block [967631] verify (1) txs and (1) inputs
20190107T010553 INFO [blockchain]  PoW block [967631] verified in (0) secs or (0) ms/input
20190107T010608 INFO [blockchain]  PoW block [967632] verify (1) txs and (1) inputs
20190107T010608 INFO [blockchain]  PoW block [967632] verified in (0) secs or (0) ms/input
20190107T010641 INFO [blockchain]  PoW block [967633] verify (1) txs and (1) inputs
20190107T010641 INFO [blockchain]  PoW block [967633] verified in (0) secs or (0) ms/input
20190107T010720 INFO [blockchain]  PoW block [967634] verify (1) txs and (1) inputs
20190107T010720 INFO [blockchain]  PoW block [967634] verified in (0) secs or (0) ms/input
20190107T010802 INFO [blockchain]  PoW block [967635] verify (1) txs and (1) inputs
20190107T010802 INFO [blockchain]  PoW block [967635] verified in (0.075) secs or (75) ms/input
20190107T011028 INFO [blockchain]  PoW block [967636] verify (1) txs and (1) inputs
20190107T011028 INFO [blockchain]  PoW block [967636] verified in (0) secs or (0) ms/input
20190107T011056 INFO [blockchain]  PoW block [967637] verify (1) txs and (1) inputs
20190107T011056 INFO [blockchain]  PoW block [967637] verified in (0) secs or (0) ms/input
20190107T011104 INFO [blockchain]  PoW block [967638] verify (1) txs and (1) inputs
20190107T011104 INFO [blockchain]  PoW block [967638] verified in (0) secs or (0) ms/input
20190107T011107 INFO [blockchain]  PoW block [967639] verify (1) txs and (1) inputs
20190107T011107 INFO [blockchain]  PoW block [967639] verified in (0) secs or (0) ms/input
20190107T011222 INFO [blockchain]  PoW block [967640] verify (1) txs and (1) inputs
20190107T011222 INFO [blockchain]  PoW block [967640] verified in (0) secs or (0) ms/input
20190107T011246 INFO [blockchain]  PoW block [967641] verify (1) txs and (1) inputs
20190107T011248 INFO [blockchain]  PoW block [967641] verified in (2.33) secs or (2330) ms/input
20190107T011335 INFO [blockchain]  PoW block [967642] verify (1) txs and (1) inputs
20190107T011338 INFO [blockchain]  PoW block [967642] verified in (3.053) secs or (3053) ms/input
20190107T011602 INFO [blockchain]  PoW block [967643] verify (1) txs and (1) inputs
20190107T011602 INFO [blockchain]  PoW block [967643] verified in (0) secs or (0) ms/input
20190107T011624 INFO [blockchain]  PoW block [967644] verify (1) txs and (1) inputs
20190107T011624 INFO [blockchain]  PoW block [967644] verified in (0) secs or (0) ms/input
20190107T011642 INFO [blockchain]  PoW block [967645] verify (1) txs and (1) inputs
20190107T011642 INFO [blockchain]  PoW block [967645] verified in (0) secs or (0) ms/input
20190107T011704 INFO [blockchain]  PoW block [967646] verify (1) txs and (1) inputs
20190107T011704 INFO [blockchain]  PoW block [967646] verified in (0) secs or (0) ms/input
20190107T011847 INFO [blockchain]  PoW block [967647] verify (1) txs and (1) inputs
20190107T011847 INFO [blockchain]  PoW block [967647] verified in (0) secs or (0) ms/input
20190107T012004 INFO [blockchain]  PoW block [967648] verify (1) txs and (1) inputs
20190107T012004 INFO [blockchain]  PoW block [967648] verified in (0) secs or (0) ms/input
20190107T012018 INFO [blockchain]  PoW block [967649] verify (1) txs and (1) inputs
20190107T012018 INFO [blockchain]  PoW block [967649] verified in (0) secs or (0) ms/input
20190107T012039 INFO [blockchain]  PoW block [967650] verify (1) txs and (1) inputs
20190107T012039 INFO [blockchain]  PoW block [967650] verified in (0) secs or (0) ms/input
20190107T012043 INFO [blockchain]  PoW block [967651] verify (1) txs and (1) inputs
20190107T012043 INFO [blockchain]  PoW block [967651] verified in (0) secs or (0) ms/input
20190107T012346 INFO [blockchain]  PoW block [967652] verify (1) txs and (1) inputs
20190107T012346 INFO [blockchain]  PoW block [967652] verified in (0) secs or (0) ms/input
20190107T012348 INFO [blockchain]  PoW block [967653] verify (1) txs and (1) inputs
20190107T012348 INFO [blockchain]  PoW block [967653] verified in (0) secs or (0) ms/input
20190107T012348 INFO [blockchain]  PoW block [967654] verify (1) txs and (1) inputs
20190107T012348 INFO [blockchain]  PoW block [967654] verified in (0) secs or (0) ms/input
20190107T012409 INFO [blockchain]  PoW block [967655] verify (1) txs and (1) inputs
20190107T012409 INFO [blockchain]  PoW block [967655] verified in (0) secs or (0) ms/input
20190107T012427 INFO [blockchain]  PoW block [967656] verify (1) txs and (1) inputs
20190107T012427 INFO [blockchain]  PoW block [967656] verified in (0) secs or (0) ms/input
20190107T012439 INFO [blockchain]  PoW block [967657] verify (1) txs and (1) inputs
20190107T012439 INFO [blockchain]  PoW block [967657] verified in (0) secs or (0) ms/input
20190107T012443 INFO [blockchain]  PoW block [967658] verify (2) txs and (3) inputs
20190107T012443 INFO [blockchain]  PoW block [967658] verified in (0) secs or (0) ms/input
20190107T012524 INFO [blockchain]  PoW block [967659] verify (1) txs and (1) inputs
20190107T012524 INFO [blockchain]  PoW block [967659] verified in (0) secs or (0) ms/input
20190107T012559 INFO [blockchain]  PoW block [967660] verify (1) txs and (1) inputs
20190107T012559 INFO [blockchain]  PoW block [967660] verified in (0) secs or (0) ms/input
20190107T012559 INFO [blockchain]  PoW block [967661] verify (1) txs and (1) inputs
20190107T012559 INFO [blockchain]  PoW block [967661] verified in (0) secs or (0) ms/input
20190107T012753 INFO [blockchain]  PoW block [967662] verify (1) txs and (1) inputs
20190107T012753 INFO [blockchain]  PoW block [967662] verified in (0) secs or (0) ms/input
20190107T012801 INFO [blockchain]  PoW block [967663] verify (1) txs and (1) inputs
20190107T012801 INFO [blockchain]  PoW block [967663] verified in (0) secs or (0) ms/input
20190107T012828 INFO [blockchain]  PoW block [967664] verify (1) txs and (1) inputs
20190107T012828 INFO [blockchain]  PoW block [967664] verified in (0) secs or (0) ms/input
20190107T012832 INFO [blockchain]  PoW block [967665] verify (1) txs and (1) inputs
20190107T012832 INFO [blockchain]  PoW block [967665] verified in (0) secs or (0) ms/input
20190107T013029 INFO [blockchain]  PoW block [967666] verify (1) txs and (1) inputs
20190107T013029 INFO [blockchain]  PoW block [967666] verified in (0) secs or (0) ms/input
Segmentation fault
[coin@localhost v0.8.5]$
[coin@localhost v0.8.5]$ ps -ef | grep mvsd
coin      4750  1574  0 01:42 pts/0    00:00:00 grep --color=auto mvsd
[coin@localhost v0.8.5]$
-------------------------------------------------------------------------------------------

**Comment by luozhaohui** [comment]
No, I could not reproduce it.
I have run './mvsd -t' over 12 hours.

**Comment by dhkstn** [comment]
It seems that there was something wrong when building the source code.
after rebuilding the image, this issue doesn't occur.
Thanks for your supporting.
