### ISSUE TITLE
What does MST mining mean?

### ISSUE THREAD

**Issue by Airead** [mvs-org/metaverse#351]
What does MST mining mean?
What is the full name of MST?
I still don't understand after reading [Guide to PoS and MST mining](https://docs.mvs.org/docs/pillars.html).

**Comment by jowenshaw** [comment]
MST mean Metaverse Smart Token, please ref. [MST introduction](https://docs.mvs.org/developers/da-index.html)

MST mining mean when you create a new block, in addition to get ETP coin reward, you can also get MST token reward in the coinbase transaction. please ref. this block on testnet as example: <https://explorer-testnet.mvs.org/blk/1071900>

**Comment by Airead** [comment]
Thank you!
