### ISSUE TITLE
[REQUEST] Make avatar name case insensitive and remove special chars

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/metaverse#397]
The Avatar name should be case insensitive to avoid confusion and to make it compatible with DNA accounts. The list of allowed special characters should also match the ones from DNA.

**Comment by vorapoap** [comment]
Is this restriction done on lightwallet or in the MVS core?

**Comment by canguruhh** [comment]
It should be implemented on the consensus (core). Case sensitivity and the removal of special characters require a soft fork. If we introduce additional characters we would need to do it during the next hardfork.

**Comment by canguruhh** [comment]
Btw. I closed this issue because its a duplicate of #354
