### ISSUE TITLE
docker build ERROR

### ISSUE THREAD

**Issue by code1010111** [mvs-org/metaverse#423]
********************** Download boost_1_69_0.tar.gz **********************

--2021-08-13 19:39:17--  https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 52.40.65.167, 52.39.193.126
Connecting to dl.bintray.com (dl.bintray.com)|52.40.65.167|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-08-13 19:39:18 ERROR 403: Forbidden.

**Comment by betachen** [comment]
the download url already be updated:

https://github.com/mvs-org/metaverse/blob/master/install_dependencies.sh#L44

**Comment by metaversedna** [comment]
Are there any tutorials for participating in the testnet?
