### ISSUE TITLE
cant sent etp

### ISSUE THREAD

**Issue by Rufus-Ruffcut** [mvs-org/metaverse#426]
Hello,

i cant send my etp the last days....
Its loading and i get the message unsuccesful http response
Can annyone help me with this?

grtz

**Comment by naftalimurgor** [comment]
Hello,

I think this project was abandoned in 2019 or 2020.

**Comment by canguruhh** [comment]
> Hello,
> 
> i cant send my etp the last days.... Its loading and i get the message unsuccesful http response Can annyone help me with this?
> 
> grtz

are you using a fullnode wallet? which version do you use? in the bottom right corner it should show the sync status. make sure that its fully synced

**Comment by betachen** [comment]
Hey, keep your wallet key in safe. you can go https://myetpwallet.com/ to send/receive etp always.

**Comment by Rufus-Ruffcut** [comment]
Hey

You  replaying a thread from 2 months ago g :p
It works fine now, thnx for the good care :)

grtz

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by canguruhh** [comment]
somehow this issue was overlooked for a long time... glad to hear that its solved

**Comment by Rufus-Ruffcut** [comment]
I think is because the forum is very hard to find on the weg...it took me a few hours to find people who could help me with a problem like this...the problem was fixed after a few days...

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
