### ISSUE TITLE
[question] master account on initial setup?

### ISSUE THREAD

**Issue by frankjs1** [mvs-org/metaverse#427]
Hi, I am newbie, please bear with me.

I have installed this on Docker successfully, currently running sync.
``mvs-cli getinfo` shows that I have 1 account:

`"wallet_account_count" : 1,`

As I don't remember entered any account creation details during setup, how do I get the details of that account (account name, password, etc.)?

Thanks in advance.

Regards

**Comment by canguruhh** [comment]
hi. you can get a list of supported commands with `mvs-cli help` the command you are looking for is `getnewaccount` followed by the username and password of your choice

https://docs.mvs.org/api_v3/account.html#getnewaccount

**Comment by canguruhh** [comment]
@frankjs1 i got your question wrong. the node comes with a default admin account. it can be used to restrict rpc access for commands like shutdown and getinfo by setting the `administrator_required` option in the [config file](https://docs.mvs.org/docs/config-file.html).
The admin username is `administerator` (pay attention to the typo) and the default password is `mvsgo`.  The account has no wallet functionality so its not possible to accidentally create addresses with it.
