### ISSUE TITLE
Building project for Docker failed

### ISSUE THREAD

**Issue by zhangwonderful** [mvs-org/metaverse#428]
Hi ,
   When I build this project for docker, it throws the following error. How can I handle it?
   Please kindly help me, thanks a lot.
E:\metaverse\metaverse-master>docker build -t metaverse -f Dockerfile .
[+] Building 11.2s (11/12)
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                    5.6s
 => [1/8] FROM docker.io/library/ubuntu:16.04@sha256:0f71fa8d4d2d4292c3c617fda2b36f6dabe5c8b6e34c3dc5b0d17d4e704b  0.0s
 => [internal] load build context                                                                                  0.4s
 => => transferring context: 105.69kB                                                                              0.4s
 => CACHED [2/8] RUN echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends   && echo 'APT::Inst  0.0s
 => CACHED [3/8] RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git-core automake autoconf libtool build-e  0.0s
 => CACHED [4/8] RUN cd /tmp && wget https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.sh   && mkdir /opt/cma  0.0s
 => CACHED [5/8] COPY ./ /tmp/metaverse/                                                                           0.0s
 => CACHED [6/8] RUN cd /tmp/metaverse && /bin/bash install_dependencies.sh --build-boost --build-upnpc            0.0s
 => ERROR [7/8] RUN cd /tmp/metaverse   && mkdir -p build && cd build && cmake .. && make -j2 && make install   &  4.8s
------
 > [7/8] RUN cd /tmp/metaverse   && mkdir -p build && cd build && cmake .. && make -j2 && make install   && rm -rf /tmp/metaverse/build   && rm -rf /tmp/metaverse/build-mvs-dependencies:
#11 1.481 -- The C compiler identification is GNU 5.4.0
#11 1.714 -- The CXX compiler identification is GNU 5.4.0
#11 1.739 -- Check for working C compiler: /usr/bin/cc
#11 1.894 -- Check for working C compiler: /usr/bin/cc -- works
#11 1.897 -- Detecting C compiler ABI info
#11 2.049 -- Detecting C compiler ABI info - done
#11 2.092 -- Detecting C compile features
#11 2.545 -- Detecting C compile features - done
#11 2.560 -- Check for working CXX compiler: /usr/bin/c++
#11 2.747 -- Check for working CXX compiler: /usr/bin/c++ -- works
#11 2.751 -- Detecting CXX compiler ABI info
#11 2.946 -- Detecting CXX compiler ABI info - done
#11 2.986 -- Detecting CXX compile features
#11 3.847 -- Detecting CXX compile features - done
#11 4.424 Boost 1.56 found.
#11 4.424 Found Boost components:
#11 4.424    date_time;filesystem;system;program_options;regex;thread
#11 4.425 CMake Error in /opt/cmake/share/cmake-3.9/Modules/FindBoost.cmake:
#11 4.425   cmake_policy PUSH without matching POP
#11 4.425 Call Stack (most recent call first):
#11 4.425   CMakeLists.txt:95 (FIND_PACKAGE)
#11 4.425
#11 4.425
#11 4.432 -- Found secp256k1: /usr/local/lib/libsecp256k1.so
#11 4.442 -- ZeroMQ version: 4.2.1
#11 4.445 -- Found ZeroMQ: /usr/local/include (found suitable version "4.2.1", minimum required is "4.2.0")
#11 4.486 -- CryptoPP not found, use existed implementation
#11 4.509 -- Looking for byteswap.h
#11 4.609 -- Looking for byteswap.h - found
#11 4.611 -- Looking for endian.h
#11 4.722 -- Looking for endian.h - found
#11 4.776 -- Configuring incomplete, errors occurred!
#11 4.776 See also "/tmp/metaverse/build/CMakeFiles/CMakeOutput.log".
#11 4.776 See also "/tmp/metaverse/build/CMakeFiles/CMakeError.log".
------
executor failed running [/bin/sh -c cd /tmp/metaverse   && mkdir -p build && cd build && cmake .. && make -j2 && make install   && rm -rf /tmp/metaverse/build   && rm -rf /tmp/metaverse/build-mvs-dependencies]: exit code: 1

**Comment by canguruhh** [comment]
fixed in branch docker-build-hotfix PR #429 is in review
