### ISSUE TITLE
Invalid account and password in v0.6.9

### ISSUE THREAD

**Issue by jiraiyav5** [mvs-org/metaverse#50]
switching wallet program vewsion will lead to the invalid loging. what's more the transaction data in the wallet can not be read !

**Comment by jiraiyav5** [comment]
@wdyoschina

**Comment by wdyoschina** [comment]
sorry, i did not see this issue before.
maybe you need to import a new account from mnemonic, because wallet account stored on your local pc.
your local database will be update after updating wallet.

**Comment by wdyoschina** [comment]
Hi jiraiyav5,
thanks for your concern, i provide the solution for you. but long time no response. I will close this issue later.
Open it again if you have any issue about that. Thanks !
